version: '3.2'
services:
  web:
    image: maxisme/mitchelldesignconsultancy.com:latest
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.mdccom.rule=Host(`mitchelldesignconsultancy.com`)"
        - "traefik.http.services.mdccom.loadbalancer.server.port=8080"
        - "traefik.http.routers.mdccom.middlewares=404"
    networks:
      - traefik

networks:
  traefik:
    external: true